### ISSUE TITLE
Improve CONTRIBUTING.md

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/.github#1]
Take more inspiration from https://docs.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors#examples-of-contribution-guidelines
For example, adding a ["What should I know before I get started?"](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#what-should-i-know-before-i-get-started) section

**Comment by choldgraf** [comment]
Could we also add a section on release cadence and philosophy? I think that our "minimal steps to make a release" approach here opens a path towards much more frequent releases in general, that I think is worth making explicit. IMO we should try to release as often as possible, sometimes even for a single commit (as a patch release anyway). That will keep the experience that users have fresh, and will reduce the amount of burden associated with major new changes to the codebase. What do others think?

**Comment by chrisjsewell** [comment]
I think we have done these things now 👍
