### ISSUE TITLE
There is no contact method provided in the Code of Conduct

### ISSUE THREAD

**Issue by pradyunsg** [executablebooks/.github#4]
The Code of Conduct does not include any description of who to contact and how to contact them, in case of CoC violations.

See https://github.com/executablebooks/.github/blob/master/CODE_OF_CONDUCT.md#enforcement

> Instances of abusive, harassing, or otherwise unacceptable behavior may be reported to the community leaders responsible for enforcement at [INSERT CONTACT METHOD]. All complaints will be reviewed and investigated promptly and fairly.

**Comment by chrisjsewell** [comment]
Ah cheers you beat me to it: @ebp-bot now has the executablebooks@gmail.com email address where these should be directed

**Comment by chrisjsewell** [comment]
closed in 9fbb9f8
